[build]
  command = "npm run build"  # Let your package.json handle the build steps
  publish = "_site"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"  # Ensures the CMS panel loads correctly
  status = 200
